spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keepstrong
    username: user
    password: password
  flyway:
    locations: classpath:db/migration
  batch:
    jdbc:
      initialize-schema: always
